### ISSUE TITLE
Multiple autoloaders

### ISSUE THREAD

**Issue by AlchemyUnited** [tommcfarlin/simple-autoloader-for-wordpress#11]
Maybe I need to do some more homework but I was under the impression that once you register an autoloader all class requests will attempt to be processed. Yet, currently, there are no tests for (more of less) "is this a class we know about or not?" 

For example, in the autoloader mentioned in the other issue (by @CarlAlexander) on line 26 he checks for:

```
if (0 !== strpos($class, 'CommentIQ')) {
return
}
```

https://github.com/postmatic/elevated-comments/blob/master/src/CommentIQ/Autoloader.php

Once you have more than one autoloader is something like this necessary? 

On the same note, prior to doing the require wouldn't it be wise to check that the file exists? Just to be safe? 

Good stuff either way. Thanks for sharing.

**Comment by tommcfarlin** [comment]
> Maybe I need to do some more homework but I was under the impression that once you register an autoloader all class requests will attempt to be processed. Yet, currently, there are no tests for (more of less) "is this a class we know about or not?"

This is a good question. Think of autoloading as being on demand, at least in the context of WordPress.

So if you try to instantiate an object that resides in a namespace, it'll look for the file based on its namespace, file name, and location on the disk. Then it will load the file and include it.

> Once you have more than one autoloader is something like this necessary?

Typically, having a single autoloader is all you need so it can be Composer or one you've manually written. 

> On the same note, prior to doing the require wouldn't it be wise to check that the file exists? Just to be safe?

Yep. And we're doing that [here](https://github.com/tommcfarlin/simple-autoloader-for-wordpress/blob/master/lib/autoload.php#L65).
