### ISSUE TITLE
Demo plugin

### ISSUE THREAD

**Issue by ArraysNL** [tommcfarlin/simple-autoloader-for-wordpress#12]
I'm a little struggling with namespaces and autoloaders, is it possible to get a demo plugin in the docs?

**Comment by tommcfarlin** [comment]
@ArraysNL Before doing that check out [this article](https://tommcfarlin.com/namespaces-and-autoloading-2017/) and see if it helps. 

If not, re-open the issue and I'll see what I can do :).
