### ISSUE TITLE
README inconsistencies

### ISSUE THREAD

**Issue by cliffordp** [tommcfarlin/simple-autoloader-for-wordpress#14]
Getting Started states:
> Add include_once 'lib/autoload.php' to your main plugin file.

but Adding The Autoloader states
> Then, at the top of your plugin file add the following: require_once 'lib/autoload.php';

So is `include_once` or `require_once` recommended?

**Comment by tommcfarlin** [comment]
I tend to prefer `require_once` because it will halt the script if the file isn't found (whereas `include_once` will try to keep going but throw a warning).

**Comment by cliffordp** [comment]
Agreed. Submitted the PR for the README
