### ISSUE TITLE
Autload WordPress core

### ISSUE THREAD

**Issue by szepeviktor** [tommcfarlin/simple-autoloader-for-wordpress#18]
https://packagist.org/packages/szepeviktor/wordpress-autoloaded

@tommcfarlin This is my first try on commenting out require-s in core and autoloading classes by Composer. Still implemented in a shell.

What do you think?

**Comment by tommcfarlin** [comment]
It looks neat; I've don't have a lot of time to go through this so I don't know if I'll have more feedback than this. Nice work.
