### ISSUE TITLE
PSR?

### ISSUE THREAD

**Issue by scofennell** [tommcfarlin/simple-autoloader-for-wordpress#3]
Not a complaint, just trying to learn from you.  What's the value here instead of a PSR autoloader ( https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md ) ?

**Comment by tommcfarlin** [comment]
This is a good question! 

**TL;DR:** [When in Rome](http://www.urbandictionary.com/define.php?term=when%20in%20rome), basically.

If a person is going to be following the [WordPress Coding Standards]() _strictly_, then this will do just that. If, however, they don't want to do so, then using PSR is fine. Or if they want to mix and match, PSR is fine.

Personally, I tend to follow WPCS when I'm working _purely_ with WordPress. Others don't always agree with my approach on this, but that's the long answer :).
