### ISSUE TITLE
PHP Requirement?

### ISSUE THREAD

**Issue by ahmadawais** [tommcfarlin/simple-autoloader-for-wordpress#4]
What is the min PHP requiement?

**Comment by pagelab** [comment]
I was about to ask the same question. Since it mentions the use of namespaces, it should be PHP => 5.3.

**Comment by tommcfarlin** [comment]
Anyone using this will be using will hopefully be on 5.4+ (though I _really_ prefer PHP7+ though I know that's still a small portion of WP users, at the moment). Developers, on the other hand, usually have more control over the server environment so the more recent, the better.

As @pagelab mentioned, [Namespaces](http://php.net/manual/en/language.namespaces.rationale.php) are supported in PHP >= 5.3.0 but this is designed for WordPress. [The minimum requirements](https://wordpress.org/about/requirements/) are PHP 5.2.4 which clearly won't support this.
