### ISSUE TITLE
Add interface support

### ISSUE THREAD

**Issue by DrewAPicture** [tommcfarlin/simple-autoloader-for-wordpress#8]
We've implemented a slightly modified version of this autoloader in a theme and needed interface support. 

Incoming PR leverages a naming convention (I know, ick) that supports both prefixing and suffixing depending on developer preference, `Interface_Foo` or `Foo_Interface`.

**Comment by DrewAPicture** [comment]
PR: #9

**Comment by DrewAPicture** [comment]
To be fair, the use of `array_search()` technically also allows for `Foo_Interface_Bar` :-P

**Comment by tommcfarlin** [comment]
Yeah - there may be some clean up I do in the future but since it's based on filenames versus anything else, I'm okay with it (until someone brings up an issue ;).
